/**
 * Centralized KIRA 2026 photo gallery data.
 *
 * Each entry pairs a real Google Drive file ID (from the public event
 * folder) with its display and download URLs. The folder is publicly
 * shared, so the standard Drive serving URLs work for any visitor.
 * No API key or credential lives in this frontend code.
 */

export interface GalleryPhoto {
  /** Zero-padded index used for counters and keys, e.g. "01". */
  id: string;
  /** Short readable label for alt text / a11y. */
  alt: string;
  /** Human caption fallback (filenames are auto-generated stamps). */
  title: string;
  /** Browser-safe filename for the Download action. */
  fileName: string;
  /** Public display URL (view only, no download prompt). */
  imageUrl: string;
  /** Public download URL for exactly this photo. */
  downloadUrl: string;
}

export const GALLERY_PHOTOS: readonly GalleryPhoto[] = [
  {
    id: '01',
    alt: 'KIRA 2026 event photo 01 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-01.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1lDmy706YWmbFblQPpSjgM-64V1coGUPq&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1lDmy706YWmbFblQPpSjgM-64V1coGUPq',
  },
  {
    id: '02',
    alt: 'KIRA 2026 event photo 02 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-02.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1KWr3KZlqRriiBL-UjjStYoKHYwFTou-r&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1KWr3KZlqRriiBL-UjjStYoKHYwFTou-r',
  },
  {
    id: '03',
    alt: 'KIRA 2026 event photo 03 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-03.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=131tY31z6Gccov9nuuSi5m0JoQP0DTbyC&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=131tY31z6Gccov9nuuSi5m0JoQP0DTbyC',
  },
  {
    id: '04',
    alt: 'KIRA 2026 event photo 04 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-04.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Jd6WJbAMogO6olv8OxyeQQ14AbN5pjWs&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1Jd6WJbAMogO6olv8OxyeQQ14AbN5pjWs',
  },
  {
    id: '05',
    alt: 'KIRA 2026 event photo 05 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-05.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1LTNREyAXlnWOrwCO-I_5mUeuE6MYHUmi&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1LTNREyAXlnWOrwCO-I_5mUeuE6MYHUmi',
  },
  {
    id: '06',
    alt: 'KIRA 2026 event photo 06 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-06.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1OIlWNZ6RfGZL4CB-BFd_RIUBdmtbv3Dt&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1OIlWNZ6RfGZL4CB-BFd_RIUBdmtbv3Dt',
  },
  {
    id: '07',
    alt: 'KIRA 2026 event photo 07 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-07.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=139tRAzz4Upx69ark0Asl2AZycA3lxwBy&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=139tRAzz4Upx69ark0Asl2AZycA3lxwBy',
  },
  {
    id: '08',
    alt: 'KIRA 2026 event photo 08 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-08.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Oeo-aODijImcyJtxi6YgRpR1m-nkz_oI&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1Oeo-aODijImcyJtxi6YgRpR1m-nkz_oI',
  },
  {
    id: '09',
    alt: 'KIRA 2026 event photo 09 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-09.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1fYC2Ci78a9rA1tHfa463zLexYy37Pgpl&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1fYC2Ci78a9rA1tHfa463zLexYy37Pgpl',
  },
  {
    id: '10',
    alt: 'KIRA 2026 event photo 10 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-10.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1-Z1ffV5zrsRABfHhjyfAHmgDbQ6IOU85&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1-Z1ffV5zrsRABfHhjyfAHmgDbQ6IOU85',
  },
  {
    id: '11',
    alt: 'KIRA 2026 event photo 11 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-11.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1qKZ4aWlucmXTU93AxVxpZPEjSkFZKFoc&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1qKZ4aWlucmXTU93AxVxpZPEjSkFZKFoc',
  },
  {
    id: '12',
    alt: 'KIRA 2026 event photo 12 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-12.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=10MIp5eCLwauidQep8QeOQsXND7LQvk_H&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=10MIp5eCLwauidQep8QeOQsXND7LQvk_H',
  },
  {
    id: '13',
    alt: 'KIRA 2026 event photo 13 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-13.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1FUuAHsxsFnLtjaccajlmLSlKy2c2skeq&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1FUuAHsxsFnLtjaccajlmLSlKy2c2skeq',
  },
  {
    id: '14',
    alt: 'KIRA 2026 event photo 14 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-14.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1RRMJj-Ews7qqZAjUWV7A7g1Hw7uMlNgv&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1RRMJj-Ews7qqZAjUWV7A7g1Hw7uMlNgv',
  },
  {
    id: '15',
    alt: 'KIRA 2026 event photo 15 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-15.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1pSqK440RnY7raF8mSEYB6OdwoApFiTru&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1pSqK440RnY7raF8mSEYB6OdwoApFiTru',
  },
  {
    id: '16',
    alt: 'KIRA 2026 event photo 16 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-16.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=11_0_TzM8HcMV4AmySmj04BuroC-dhPP4&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=11_0_TzM8HcMV4AmySmj04BuroC-dhPP4',
  },
  {
    id: '17',
    alt: 'KIRA 2026 event photo 17 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-17.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=14SE9e8y5i_NsL8u9jcpEv6fdI9Jq3Vdn&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=14SE9e8y5i_NsL8u9jcpEv6fdI9Jq3Vdn',
  },
  {
    id: '18',
    alt: 'KIRA 2026 event photo 18 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-18.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1b2Fjpb7mTswbl1VRHQYQPDgf9aJ0Zol4&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1b2Fjpb7mTswbl1VRHQYQPDgf9aJ0Zol4',
  },
  {
    id: '19',
    alt: 'KIRA 2026 event photo 19 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-19.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Yphrsr2AcOHz1KxeohePMGKh8cF8wWZm&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1Yphrsr2AcOHz1KxeohePMGKh8cF8wWZm',
  },
  {
    id: '20',
    alt: 'KIRA 2026 event photo 20 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-20.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1f8eCm68jle115g2ROF-H_Cs0s5qvFcvC&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1f8eCm68jle115g2ROF-H_Cs0s5qvFcvC',
  },
  {
    id: '21',
    alt: 'KIRA 2026 event photo 21 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-21.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1VwjZrPeD1zLl2n02aCyTVy5glfFuAErS&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1VwjZrPeD1zLl2n02aCyTVy5glfFuAErS',
  },
  {
    id: '22',
    alt: 'KIRA 2026 event photo 22 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-22.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1EXj8RepzSzbUL9_PrX-ZThNY7j_XIbMd&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1EXj8RepzSzbUL9_PrX-ZThNY7j_XIbMd',
  },
  {
    id: '23',
    alt: 'KIRA 2026 event photo 23 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-23.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1WfhpuAyCWI7vHbqNPCCEcDHVhx0pm_sJ&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1WfhpuAyCWI7vHbqNPCCEcDHVhx0pm_sJ',
  },
  {
    id: '24',
    alt: 'KIRA 2026 event photo 24 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-24.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1ku8iT_KBIz2IbmLA2IW7oOxV_ya8aLxQ&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1ku8iT_KBIz2IbmLA2IW7oOxV_ya8aLxQ',
  },
  {
    id: '25',
    alt: 'KIRA 2026 event photo 25 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-25.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1GZFwnbZlWhA7QkNd554BZ22kQ0wQAkEn&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1GZFwnbZlWhA7QkNd554BZ22kQ0wQAkEn',
  },
  {
    id: '26',
    alt: 'KIRA 2026 event photo 26 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-26.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1OwpZxHluTJ8xMI3KO4OQ07xQTwT3o6W7&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1OwpZxHluTJ8xMI3KO4OQ07xQTwT3o6W7',
  },
  {
    id: '27',
    alt: 'KIRA 2026 event photo 27 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-27.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1rn3geZqv8YRhjFPFSRgUSmQ2smUhu8Wg&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1rn3geZqv8YRhjFPFSRgUSmQ2smUhu8Wg',
  },
  {
    id: '28',
    alt: 'KIRA 2026 event photo 28 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-28.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1v5ePfTEeZ_HmlMrd50XRRVBCty-nLtV7&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1v5ePfTEeZ_HmlMrd50XRRVBCty-nLtV7',
  },
  {
    id: '29',
    alt: 'KIRA 2026 event photo 29 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-29.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Q-X5hmowFWwbUNVBd2vmW3cYcA_za53D&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1Q-X5hmowFWwbUNVBd2vmW3cYcA_za53D',
  },
  {
    id: '30',
    alt: 'KIRA 2026 event photo 30 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-30.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1NPyFhDOxXSevNz3r7jhn4-K7l1wM2p8x&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1NPyFhDOxXSevNz3r7jhn4-K7l1wM2p8x',
  },
  {
    id: '31',
    alt: 'KIRA 2026 event photo 31 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-31.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1wBmnJKtOlfmolAirdYkmRJu2K-WS0Zpn&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1wBmnJKtOlfmolAirdYkmRJu2K-WS0Zpn',
  },
  {
    id: '32',
    alt: 'KIRA 2026 event photo 32 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-32.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1rB9SiaSQ8SGWNX5p0y4MYcxYHsSbcLpO&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1rB9SiaSQ8SGWNX5p0y4MYcxYHsSbcLpO',
  },
  {
    id: '33',
    alt: 'KIRA 2026 event photo 33 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-33.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=16BHEKO7seitRpn8DNo3WeDhH7uLaE8cA&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=16BHEKO7seitRpn8DNo3WeDhH7uLaE8cA',
  },
  {
    id: '34',
    alt: 'KIRA 2026 event photo 34 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-34.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1aROSoUkuwmsQcCdhe3ODNGMH4Y41hLNL&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1aROSoUkuwmsQcCdhe3ODNGMH4Y41hLNL',
  },
  {
    id: '35',
    alt: 'KIRA 2026 event photo 35 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-35.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1mNybwHlVmbrfEgbJtzYvJfT1IvAxf1-8&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1mNybwHlVmbrfEgbJtzYvJfT1IvAxf1-8',
  },
  {
    id: '36',
    alt: 'KIRA 2026 event photo 36 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-36.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=179r-7gEBY4nCGsCfXMDETxgevF2YpoRC&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=179r-7gEBY4nCGsCfXMDETxgevF2YpoRC',
  },
  {
    id: '37',
    alt: 'KIRA 2026 event photo 37 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-37.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1R5k2HTEPA1s6UpykOmMqqmruMACMKOeG&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1R5k2HTEPA1s6UpykOmMqqmruMACMKOeG',
  },
  {
    id: '38',
    alt: 'KIRA 2026 event photo 38 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-38.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1sXXAVEH7Rt71OYnMTccXPh2RBF_AUV_z&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1sXXAVEH7Rt71OYnMTccXPh2RBF_AUV_z',
  },
  {
    id: '39',
    alt: 'KIRA 2026 event photo 39 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-39.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=175I9SxDQVpCBWLxhpB2gLbkAomY48_Ce&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=175I9SxDQVpCBWLxhpB2gLbkAomY48_Ce',
  },
  {
    id: '40',
    alt: 'KIRA 2026 event photo 40 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-40.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1xvzUtj2PWcuKNL1O5aTlXrR_0SRcj-vO&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1xvzUtj2PWcuKNL1O5aTlXrR_0SRcj-vO',
  },
  {
    id: '41',
    alt: 'KIRA 2026 event photo 41 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-41.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1ugHJEGGZpBl-XZcNu7VADU3eLMklOGlp&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1ugHJEGGZpBl-XZcNu7VADU3eLMklOGlp',
  },
  {
    id: '42',
    alt: 'KIRA 2026 event photo 42 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-42.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Tytoyq71fy9PgU-X6YAv_bbnKNa8Gb3U&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1Tytoyq71fy9PgU-X6YAv_bbnKNa8Gb3U',
  },
  {
    id: '43',
    alt: 'KIRA 2026 event photo 43 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-43.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1kwun4GHKV6YVkdwaeHaJg_G64pef31DX&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1kwun4GHKV6YVkdwaeHaJg_G64pef31DX',
  },
  {
    id: '44',
    alt: 'KIRA 2026 event photo 44 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-44.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1-jcHaKKR59FKQbZ0zbuUBe2-uvBYpzD9&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1-jcHaKKR59FKQbZ0zbuUBe2-uvBYpzD9',
  },
  {
    id: '45',
    alt: 'KIRA 2026 event photo 45 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-45.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1i5V5riqYk1c-4c6YgSrCGC2xiPwxCx3G&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1i5V5riqYk1c-4c6YgSrCGC2xiPwxCx3G',
  },
  {
    id: '46',
    alt: 'KIRA 2026 event photo 46 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-46.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=18AToL0oRlu-jG_22fiJVGbgG0g5qaAMh&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=18AToL0oRlu-jG_22fiJVGbgG0g5qaAMh',
  },
  {
    id: '47',
    alt: 'KIRA 2026 event photo 47 of 47',
    title: 'KIRA 2026 · Event Moments',
    fileName: 'KIRA-2026-photo-47.jpg',
    imageUrl: 'https://drive.google.com/thumbnail?id=1YkHaHpNvJ5DpC7DzYwluJmEEKUwF4AaO&sz=w1600',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=1YkHaHpNvJ5DpC7DzYwluJmEEKUwF4AaO',
  },
];

export const GALLERY_TOTAL = GALLERY_PHOTOS.length;
